language: node_js
node_js:
  - 'stable'
  - 'lts/*'
deploy:
  provider: npm
  email: hermanmiller.dkr@gmail.com
  on:
    tags: true
  api_key:
    secure: cUUR9Ugj2UjJ0lhrPs1T5tjFO4JlThX3p3TaJXNiPZFVzwsaotzrm/Cp0Ib8xLvjdThD64RkjdNQ60/Sdl2Nd6qL6LJnMXdUPTAsXGTBrOSLPZMWwLL0ZdYvoCI0iangxcxMd45v8Dp0ZvDSWD4pQ6YhBNcF1VQ472sH/fBbE/lw9qr0xsyaLvT38iVeO7q2Gi2TXkVCMWiZp8+yw/bm1EmYL8OxizncljFrjCw9kXjJ7p07Cp86HdX2iAh43OQNyrC6tI6Bvd4o7MDL3JEQxScThS+A0Key5gLbcChZiLggbhI+G+hamdKyBtAXWCup0R6eQ+voosaeocupbFdJpR9DFRwt2/WoiY44YSUl8e4syAlJvI+/jN+1RNsG9depHrfY3+J2wY37Km5/4YHthazvoOnoNPcoMDmWs2HfzWfZbdP9KQzEC1jRWtykyFyUJeRuEz+QP89ohtU36Ls6z675+eLmgioI6VKouqQiLwd9VQ5CbNt4IGeuY2dApIvnuI2BQY2DvXULCXtmq7TSrLiHphkVVo3X/xr2ZxZvgE9GmSLgC18grAnFaeSaUSZM9NosTE3Tn742kIohi/t4gUUFwd/gso5n70ltBS2Hry1ViI08iuWSETLqVY9IrW5vAQqb9xObfde2Rkpv8SeQsrYFmIhQu6dlsTGPhuhwV0Q=
services:
  - xvfb
