language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: hermanmiller.dkr@gmail.com
  on:
    tags: true
  api_key:
    secure: MRPsIbwJ9ri5tnlpSeuaV1e9CYWlYPCtmbPcxb5fgXXHqA6Qq4yrSICEJSPUac2sEjNJQ/HSWnlF4K1fglws+12/pPrgKFSQeYP57mv9FGrggyvBhiMqRQv0ZtW3r5CPwQanMKG5Cbti1ZC2egpXVjXn6ot976kaIaDwgdyzjK7S8sxyRHR47tbEzfNmn1sOqdT/iAzhU1o7E9DS1smQVBgJn3f9+09YR4qXocQSuwS2uHFdd/DdCu04zK2OkFKj6Q/dmPEuvZioWBproRH3I0Zy1RT2eITLZoPCt2zKY2dixWgYvy86JWkwMjoN3jwWl2PrEDp1KQtiVLnJsiUaD6AR3iba3XUmJYNcSMoORX9Fcr6RpF6Z/tl6d7rBV4ddjksdu9TtNwznxemu4DsMskFYYJKt5Tn0xEaZq5AwyHKVvKZNO/lJM6/CZaG3zaFzYVtyro8U3Mm/CqzkEtskeIYPyR+0QebZ5ZRCx/vwYDymeVBWZVnf16HkCfD22rIiIngpyQIrSK8lp633zQ4xPPtMspJVnAgbX4+b2Zd4gCMWftOzquyPY6rsIWW93/IUtn/xNQqpx2Q+YFT6SIEFLmh5u6JUTUscaSN/kycNZ8YtdVzRoJMIo/qP8HQXfWt0PqrecDnFn83RBLVHcb2kvHOdY05yjym/U3UJiOK+1P8=